feat: rename helm deployment
LegitSecurity/kubernetes-agent pull request #5
Opened 2023-04-17 20:42 UTC by yair-legit

2023-05-07 14:58 UTC, amith-legit requested changes
Left some comments to fix
Also, I think we should split the chart into a different customer-facing repo and make this repo private

2023-05-07 14:58 UTC, amith-legit commented on helm-chart/templates/deployment.yaml
> +  name: legit-kubernetes-agent
names should come from the Helm metavariables. See my comment in `rbac.yaml`

2023-05-07 14:58 UTC, amith-legit commented on helm-chart/Chart.yaml
>  description: A Helm chart for Kubernetes that connects the cluster for creating code to cloud integration
description: A Helm chart for Kubernetes that connects the cluster to the Legit Security platform

2023-05-07 14:58 UTC, amith-legit commented on helm-chart/templates/rbac.yaml
> +  name: legit-kubernetes-agent-role
for labels you can also use the macro kubernetes-agent.labels you defined

2023-05-07 14:58 UTC, amith-legit commented on helm-chart/templates/serviceaccount.yaml
> +  name: legit-kubernetes-agent-sa
Name needs to come from helm metavariables

2023-05-07 14:58 UTC, amith-legit commented on helm-chart/templates/deployment.yaml
> +      {{- include "kubernetes-agent.labels" . | nindent 6 }}
selectorLabels

2023-05-07 14:58 UTC, amith-legit commented on helm-chart/templates/deployment.yaml
> +            {{- include "kubernetes-agent.labels" . | nindent 8 }}
selectorLabels

2023-05-07 14:58 UTC, amith-legit commented on helm-chart/templates/deployment.yaml
> +      serviceAccountName: legit-kubernetes-agent-sa
name from metavariables

2023-05-07 14:58 UTC, amith-legit commented on helm-chart/templates/deployment.yaml
> +      serviceAccountName: legit-kubernetes-agent-sa
also add a securityContext option
(and see https://github.com/epsagon/helm-charts/blob/main/charts/cluster-agent/templates/cluster-agent-deployment.yaml)

2023-05-07 14:58 UTC, amith-legit commented on helm-chart/templates/deployment.yaml
>          - name: {{ .Chart.Name }}-broker
name this agent, avoid mentioning the broker

2023-05-07 14:58 UTC, amith-legit commented on helm-chart/templates/deployment.yaml
>          - name: {{ .Chart.Name }}-broker
also in values.yaml this shouldn't be legitBroker, you can use agent token, agent identifier, or you can suggest another id

2023-05-07 14:58 UTC, amith-legit commented on helm-chart/templates/deployment.yaml
Add a `nodeSelector`, `affinity`, and `tolerations` sections at the end.
Again, see https://github.com/epsagon/helm-charts/blob/main/charts/cluster-agent/templates/cluster-agent-deployment.yaml

2023-05-07 14:58 UTC, amith-legit commented on .github/workflows/pipeline.yml
> +          && helm lint . \
How does this work? when did you install helm?

2023-05-07 14:58 UTC, amith-legit commented on .github/workflows/pipeline.yml
> +      - name: helm-lint
I think it's preferable to use https://github.com/helm/chart-testing-action

2023-05-09 08:18 UTC, amith-legit requested changes
Almost everything is good, this should be the final round

2023-05-09 08:18 UTC, amith-legit commented on helm-chart/templates/deployment.yaml
> +      serviceAccountName: {{ template "kubernetes-agent.fullname" . }}
Should be the helper serviceAccountName

2023-05-09 08:18 UTC, amith-legit commented on helm-chart/templates/deployment.yaml
>             - name: BROKER_IDENTIFIER
I'm sorry I missed that, but this should be in a secret

2023-05-09 08:18 UTC, amith-legit commented on helm-chart/templates/rbac.yaml
> +  name: {{ .Chart.Name }}
also add labels

2023-05-09 08:18 UTC, amith-legit commented on helm-chart/templates/serviceaccount.yaml
>  apiVersion: v1
This section should be enclosed in {{- if .Values.serviceAccount.create -}}

2023-05-09 08:18 UTC, amith-legit commented on helm-chart/templates/deployment.yaml
>        labels:
also add anotations

2023-05-09 08:18 UTC, amith-legit commented on helm-chart/values.yaml
I know the example I shared isn't 10/10 on this either, but we can't have any "ghost" values here. i.e. values that aren't included in the chart, because that's very frustrating for the user.

2023-05-09 08:42 UTC, yair-legit commented on helm-chart/templates/serviceaccount.yaml
>  apiVersion: v1
but we always need to create a serviceAccount for us no?

2023-05-16 22:12 UTC, yair-legit commented on helm-chart/templates/deployment.yaml
>             - name: BROKER_IDENTIFIER
this means creating a new cluster instance (secret) do we really want this?

2023-05-17 07:59 UTC, amith-legit reviewed
Very close. I think this will be the final round

2023-05-17 07:59 UTC, amith-legit commented on helm-chart/templates/serviceaccount.yaml
>  apiVersion: v1
Not done

2023-05-17 07:59 UTC, amith-legit commented on helm-chart/values.yaml
> +  identifier: "aa" # Your broker identifier goes here
Better to have this empty

2023-05-17 07:59 UTC, amith-legit commented on helm-chart/templates/deployment.yaml
>             - name: BROKER_IDENTIFIER
discussed

2023-05-17 07:59 UTC, amith-legit commented on helm-chart/values.yaml
> +  #proxy: # If the broker needs a proxy to access the Legit app, set it here (e.g http://example.com)
This variable is unused

2023-05-17 08:01 UTC, yair-legit commented on helm-chart/values.yaml
> +  identifier: "aa" # Your broker identifier goes here
mistake :(

2023-05-17 08:17 UTC, yair-legit commented on helm-chart/templates/serviceaccount.yaml
>  apiVersion: v1
<img width="1359" alt="image" src="https://github.com/LegitSecurity/kubernetes-agent/assets/113283158/4753e277-803a-4f08-b3c2-2adb339386e2">
?

2023-05-17 11:26 UTC, amith-legit approved these changes

2023-05-17 11:36 UTC, yair-legit commented
DEV-3163

2023-05-17 11:36 UTC, merged